---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.9.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn-system
  values:
    ingress:
      enabled: true
      host: longhorn.homelab
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: homelab-ca-issuer
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hajimari.io/enable: "true"
        hajimari.io/appName: "Longhorn"
        hajimari.io/icon: "mdi:network-attached-storage"
        hajimari.io/url: "https://longhorn.homelab/"
        hajimari.io/targetBlank: "true"
        hajimari.io/info: "Dashboard for Longhorn"
      path: /
      tls:
        - hosts:
            - longhorn.homelab
          secretName: wildcard-homelab-tls
      pathType: Prefix

    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
        annotations: {}
        interval: "30s"
        scrapeTimeout: ""
        relabelings: []
        metricRelabelings: []
