---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.9.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn-system
  values:
    ingress:
      enabled: true
      host: longhorn.homelab
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: homelab-ca-issuer
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      path: /
      tls:
        - hosts:
            - longhorn.homelab
          secretName: wildcard-homelab-tls
      pathType: Prefix

    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
      namespace: longhorn-system
      interval: 30s
      labels:
        release: kube-prometheus-stack
