---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: longhorn
      version: v1.9.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
        namespace: longhorn-system
  values: 
  # Add in helm values here
