apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik
spec:
  interval: 1h 
  chart:
    spec:
      chart: authentik
      version: 2023.10.7
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: authentik
  valuesFrom:
    - kind: Secret
      name: authentik-secret-key
      valuesKey: values.yaml
  values:
    redis:
      enabled: true
      storageClass: longhorn
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    server: 
      startupProbe:
        httpGet:
          path: "/-/health/live/"
          port: 9000
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 60
      ingress:
        enabled: true
        ingressClassName: nginx
        host: authentik.homelab
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - authentik.homelab
            secretName: authentik-tls
        annotations:
          cert-manager.io/cluster-issuer: homelab-ca-issuer
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/rewrite-target: /
          hajimari.io/enable: "true"
          hajimari.io/appName: "Authentik"
          hajimari.io/icon: "mdi:account-key"
          hajimari.io/url: "https://authentik.homelab/"
          hajimari.io/targetBlank: "true"
          hajimari.io/info: "Authentik Admin Page"

    prometheus:
      serviceMonitor:
        enabled: true
        namespace: authentik
        labels:
          release: kube-prometheus-stack
