apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik-release
  app: authentik-release
spec:
  interval: 1h 
  chart:
    spec:
      chart: authentik
      version: 2025.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: authentik
  valuesFrom:
    - kind: Secret
      name: authentik-secret-key
      valuesKey: values.yaml
  values:
    redis:
      enabled: true
      storageClass: longhorn
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    server:
      metrics:
        enabled: true
        service:
          portName: metrics
          servicePort: 9300
          type: ClusterIP
        serviceMonitor:
          enabled: true
          namespace: authentik
          interval: "30s"
          scrapeTimeout: "10s"  # adjust as needed
          labels:
            release: kube-prometheus-stack
          selector:
            matchLabels:
              release: kube-prometheus-stack
