apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik-release
  namespace: authentik
spec:
  interval: 1h 
  chart:
    spec:
      chart: authentik
      version: 2023.10.7
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: authentik
  valuesFrom:
    - kind: Secret
      name: authentik-secret-key
      valuesKey: values.yaml
  values:
    redis:
      enabled: true
      storageClass: longhorn
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    prometheus:
      serviceMonitor:
        enabled: true
        namespace: authentik
        labels:
          release: kube-prometheus-stack
