apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  interval: 1m0s
  values:
    installCRDs: true      
