apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-homelab-cert
  namespace: default
spec:
  commonName: '*.homelab'
  dnsNames:
  - '*.homelab'
  secretName: wildcard-homelab-tls
  duration: 2160h # 90 days
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
