---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-repo
  interval: 1h
  values: 
    controller:
      admissionWebhooks:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/enable-external-auth: "true"
      allowSnippetAnnotations: true
      config:
        strict-validate-path-type: "false"
        enable-underscores-in-headers: "true"    
        enable-annotation-validation: "false"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
        port: 10254
        portName: metrics
