---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-repo
  interval: 1h
  values: 
    controller:
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
        port: 10254
        portName: metrics
