apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: homelab-ca-issuer
        hosts:
          - prometheus.homelab
        tls:
          - hosts:
              - prometheus.homelab
            secretName: wildcard-homelab-tls

    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: homelab-ca-issuer
        hosts:
          - alertmanager.homelab
        tls:
          - hosts:
              - alertmanager.homelab
            secretName: wildcard-homelab-tls

    grafana:
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: homelab-ca-issuer
        hosts:
          - grafana.homelab
        tls:
          - hosts:
              - grafana.homelab
            secretName: wildcard-homelab-tls
