apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 74.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - prometheus.homelab
        tls:
          - hosts:
              - prometheus.homelab
            secretName: wildcard-homelab

    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - alertmanager.homelab
        tls:
          - hosts:
              - alertmanager.homelab
            secretName: wildcard-homelab

    grafana:
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - grafana.homelab
        tls:
          - hosts:
              - grafana.homelab
            secretName: wildcard-homelab
