apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics-config.yaml
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 15Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: homelab-ca-issuer
          hajimari.io/enable: "true"
          hajimari.io/appName: "Prometheus"
          hajimari.io/icon: "simple-icons:prometheus"
          hajimari.io/url: "https://prometheus.homelab/"
          hajimari.io/targetBlank: "true"
          hajimari.io/info: "Prometheus Web UI"
          nginx.ingress.kubernetes.io/auth-url: |
            http://ak-outpost-authentik.authentik.svc.cluster.local:9000/outpost/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |
            https://authentik.homelab/outpost/start?rd=$scheme://$http_host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - prometheus.homelab
        tls:
          - hosts:
              - prometheus.homelab
            secretName: prometheus-tls

    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 2Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: homelab-ca-issuer
          hajimari.io/enable: "true"
          hajimari.io/appName: "Alert Manager"
          hajimari.io/icon: "mdi:bell-alert"
          hajimari.io/url: "https://alertmanager.homelab/"
          hajimari.io/targetBlank: "true"
          hajimari.io/info: "Prometheus Alert Manager"
        hosts:
          - alertmanager.homelab
        tls:
          - hosts:
              - alertmanager.homelab
            secretName: alertmanager-tls

    grafana:
      persistence:
        enabled: true
        accessModes: ["ReadWriteMany"]
        storageClassName: longhorn
        size: 5Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: homelab-ca-issuer
          hajimari.io/enable: "true"
          hajimari.io/appName: "Grafana"
          hajimari.io/icon: "simple-icons:grafana"
          hajimari.io/url: "https://grafana.homelab/"
          hajimari.io/targetBlank: "true"
          hajimari.io/info: "Metric Visualization Dashboards"
        hosts:
          - grafana.homelab
        tls:
          - hosts:
              - grafana.homelab
            secretName: grafana-tls
